language: objective-c
osx_image: xcode7

git:
  submodules: false

before_install:
    - git submodule update --init --recursive

script:
    - set -o pipefail && xcodebuild -workspace DiceKit.xcworkspace -scheme DiceKit -sdk macosx test | xcpretty -c
    - set -o pipefail && xcodebuild -workspace DiceKit.xcworkspace -scheme DiceKit -sdk iphonesimulator test | xcpretty -c
    - set -o pipefail && xcodebuild -workspace DiceKit.xcworkspace -scheme DiceKit -sdk watchsimulator analyze | xcpretty -c

notifications:
  email:
    on_success: change
    on_failure: change
